### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/infobip#1]
- [x] Code Review
- [x] Add to website
- [x] Create packagist package
- [x] Github actions
- [x] Style CI
- [x] Scrutinizer 
- [x] Add badges

**Comment by tomsgad** [comment]
@atymic please check the PR

**Comment by atymic** [comment]
@tomsgad 

```Reading composer.json of laravel-notification-channels/infobip (master)
Importing branch master (dev-master)
Skipped branch master, Invalid package information:
authors.0.homepage : invalid value (httsp://magurutechnologies.com), must be an http/https URL
```

**Comment by tomsgad** [comment]
> @tomsgad
> 
> ```
> Importing branch master (dev-master)
> Skipped branch master, Invalid package information:
> authors.0.homepage : invalid value (httsp://magurutechnologies.com), must be an http/https URL
> ```

Fixed!

**Comment by atymic** [comment]
Launched :)
